"""Update Territory model with buildings and apartments columns

Revision ID: 158631f0e7a5
Revises: reset_territory_sequence
Create Date: 2024-12-08 14:47:05.541336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '158631f0e7a5'
down_revision = 'reset_territory_sequence'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buildings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('apartments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.drop_constraint('territory_uuid_key', type_='unique')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('apartment_count')
        batch_op.drop_column('uuid')
        batch_op.drop_column('building_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apartment_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('territory_uuid_key', ['uuid'])
        batch_op.alter_column('coordinates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('apartments')
        batch_op.drop_column('buildings')

    # ### end Alembic commands ###
