"""Ajout de la colonne sonnettes à Territory

Revision ID: ad1357c5db0f
Revises: e02a6f7b3e1f
Create Date: 2024-12-08 15:48:54.972668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1357c5db0f'
down_revision = 'e02a6f7b3e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sonnettes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.drop_column('sonnettes')

    # ### end Alembic commands ###
