"""Add commentaire field to Territory

Revision ID: d6c86b69f9f9
Revises: ad1357c5db0f
Create Date: 2024-12-08 23:57:00.791324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c86b69f9f9'
down_revision = 'ad1357c5db0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.drop_column('commentaire')

    # ### end Alembic commands ###
